#!/bin/bash

set -euxo pipefail

readonly tempdir=$(mktemp -t update-requirements -d)
readonly venvdir=${tempdir}/venv

python3 -m virtualenv ${venvdir}
${venvdir}/bin/pip install --requirement requirements-minimal.txt
${venvdir}/bin/pip freeze > requirements.txt
