#!/bin/bash

set -euxo pipefail

usage() {
    cat <<EOF
Usage: $0 [package]

-h | --help         Get help
EOF
}

if test -z "$@"
then
    usage
    exit 1
fi

for arg in "$@"
do
    if test ${arg} = "-h" || test ${arg} = "--help"
    then
        usage
        exit 0
    fi
done

readonly tempdir=$(mktemp -t update-python-build -d)
readonly venvdir=${tempdir}/venv-${1}

python3 -m virtualenv ${venvdir}
${venvdir}/bin/pip install --requirement ${1}/requirements-minimal.txt
${venvdir}/bin/pip freeze > ${tempdir}/requirements.txt

/usr/bin/sed -i "" 's/==.*/"),/g' ${tempdir}/requirements.txt
/usr/bin/sed -i "" 's/^/    requirement("/g' ${tempdir}/requirements.txt

echo 'load("@pydeps//:requirements.bzl", "requirement")' > ${1}/pydeps.bzl
echo '' >> ${1}/pydeps.bzl
echo 'import_deps = [' >> ${1}/pydeps.bzl
cat ${tempdir}/requirements.txt >> ${1}/pydeps.bzl
echo ']' >> ${1}/pydeps.bzl
